version: 2.1

jobs:
  run_tests:
      machine:
        image: ubuntu-2004:202111-01
      steps:
        - checkout
        - run: docker run -t -v `pwd`:/app/test balrrach/instant-eat:latest

  compile_stable:
      docker:
        - image: node:latest
      steps:
        - checkout
        - run: npm install typescript

  compile_latest:
      docker:
        - image: node:latest
      steps:
        - checkout
        - run: npm install typescript@next

  compile_minimum:
      docker:
        - image: node:latest
      steps:
        - checkout
        - run: npm install typescript@3.7.5

workflows:
  ci:
    jobs:
      - compile_stable
      - compile_latest
      - compile_minimum
