name: Run Tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.set-output.outputs.has_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get pr metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: balrrach/instant-eat
      - name: Run tests in the container
        env:
          CONTAINER: ${{ steps.meta.output.labels }}
        run: docker run -t -v `pwd`:/app/test ${CONTAINER,,}
