name: Run Tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get PR metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: balrrach/instant-eat
      - name: Run tests in the container
          CONTAINER: ${{ steps.meta.outputs.tags }}
          # CONTAINER: ${{ steps.meta.outputs.labels }}
        run: docker run -t -v "`pwd`:/app/test" "${CONTAINER}"
