name: Update Main Container
on:
  push:
    branches:
      - 'main'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.set-output.outputs.has_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Comprobar qué archivos han cambiado
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          since_last_remote_commit: 'true'

      - name: Comprobar si el Dockerfile o las dependencias han cambiado
        id: set-output
        if: |
          contains(steps.changed-files.outputs.modified_files, 'Dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'package.json')
        run: echo '::set-output name=has_changed::true'

  build-container:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.update
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login en Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_HUB_USERNAME  }}
          password: ${{  secrets.DOCKER_HUB_PASSWORD  }}

      - name: Extraer metadatos (tags, labels) para Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: balrrach/instant-eat
        
      - name: build y push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: balrrach/instant-eat:latest
          labels: ${{  steps.meta.outputs.labels  }}
