name: Update PR Container

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'package.json'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login en Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_HUB_USERNAME  }}
          password: ${{  secrets.DOCKER_HUB_PASSWORD  }}

      - name: Extraer metadatos (tags, labels) para Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: balrrach/instant-eat
        
      - name: build y push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # tags: ${{  steps.meta.outputs.tags  }}
          tags: latest
          labels: ${{  steps.meta.outputs.labels  }}
