name: Publicar a Dockerhub
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
    - main

jobs:
  dockerfile-changes:
    runs-on: ubuntu-latest
    outputs:
      ha_cambiado: ${{ steps.set_output.outputs.si }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Comprobar qué archivos han cambiado
        id: changed-files
        uses: tj-actions/changed-files@v1.2.0

      - name: Dockerfile o requerimientos han cambiado
        id: set_output
        if: |
          contains(steps.changed-files.outputs.modified_files, 'Dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'package.json')
        run: "::set-output name=ha_cambiado::true"

  build-container:
    runs-on: ubuntu-latest
    needs: dockerfile-changes
    if: needs.dockerfile-changes.outputs.ha_cambiado
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login en Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_HUB_USERNAME  }}
          password: ${{  secrets.DOCKER_HUB_PASSWORD  }}

      - name: Extraer metadatos (tags, labels) para Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: balrrach/instant-eat

      - name: build y push
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          tags: ${{  steps.meta.outputs.tags  }}
          labels: ${{  steps.meta.output.labels  }}
